// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.21.1
// source: carModelIdf.proto

package proto

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdfRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	ImgType       string `protobuf:"bytes,1,opt,name=ImgType,proto3" json:"ImgType,omitempty"`
	ImgUrlOrBytes string `protobuf:"bytes,2,opt,name=ImgUrlOrBytes,proto3" json:"ImgUrlOrBytes,omitempty"`
}

func (x *IdfRequest) Reset() {
	*x = IdfRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carModelIdf_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdfRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdfRequest) ProtoMessage() {}

func (x *IdfRequest) ProtoReflect() protoreflect.Message {
	mi := &file_carModelIdf_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdfRequest.ProtoReflect.Descriptor instead.
func (*IdfRequest) Descriptor() ([]byte, []int) {
	return file_carModelIdf_proto_rawDescGZIP(), []int{0}
}

func (x *IdfRequest) GetImgType() string {
	if x != nil {
		return x.ImgType
	}
	return ""
}

func (x *IdfRequest) GetImgUrlOrBytes() string {
	if x != nil {
		return x.ImgUrlOrBytes
	}
	return ""
}

type IdfResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id    int64     `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Color string    `protobuf:"bytes,2,opt,name=Color,proto3" json:"Color,omitempty"`
	Size  *CarSize  `protobuf:"bytes,3,opt,name=Size,proto3" json:"Size,omitempty"`
	Model *CarModel `protobuf:"bytes,4,opt,name=Model,proto3" json:"Model,omitempty"`
}

func (x *IdfResponse) Reset() {
	*x = IdfResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carModelIdf_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdfResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdfResponse) ProtoMessage() {}

func (x *IdfResponse) ProtoReflect() protoreflect.Message {
	mi := &file_carModelIdf_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdfResponse.ProtoReflect.Descriptor instead.
func (*IdfResponse) Descriptor() ([]byte, []int) {
	return file_carModelIdf_proto_rawDescGZIP(), []int{1}
}

func (x *IdfResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *IdfResponse) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *IdfResponse) GetSize() *CarSize {
	if x != nil {
		return x.Size
	}
	return nil
}

func (x *IdfResponse) GetModel() *CarModel {
	if x != nil {
		return x.Model
	}
	return nil
}

type CarSize struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Height int32 `protobuf:"varint,1,opt,name=Height,proto3" json:"Height,omitempty"`
	Left   int32 `protobuf:"varint,2,opt,name=Left,proto3" json:"Left,omitempty"`
	Top    int32 `protobuf:"varint,3,opt,name=Top,proto3" json:"Top,omitempty"`
	Width  int32 `protobuf:"varint,4,opt,name=Width,proto3" json:"Width,omitempty"`
}

func (x *CarSize) Reset() {
	*x = CarSize{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carModelIdf_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarSize) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarSize) ProtoMessage() {}

func (x *CarSize) ProtoReflect() protoreflect.Message {
	mi := &file_carModelIdf_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarSize.ProtoReflect.Descriptor instead.
func (*CarSize) Descriptor() ([]byte, []int) {
	return file_carModelIdf_proto_rawDescGZIP(), []int{2}
}

func (x *CarSize) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CarSize) GetLeft() int32 {
	if x != nil {
		return x.Left
	}
	return 0
}

func (x *CarSize) GetTop() int32 {
	if x != nil {
		return x.Top
	}
	return 0
}

func (x *CarSize) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

type CarModel struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name  string  `protobuf:"bytes,1,opt,name=Name,proto3" json:"Name,omitempty"`
	Year  string  `protobuf:"bytes,2,opt,name=Year,proto3" json:"Year,omitempty"`
	Score float64 `protobuf:"fixed64,3,opt,name=Score,proto3" json:"Score,omitempty"`
}

func (x *CarModel) Reset() {
	*x = CarModel{}
	if protoimpl.UnsafeEnabled {
		mi := &file_carModelIdf_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CarModel) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CarModel) ProtoMessage() {}

func (x *CarModel) ProtoReflect() protoreflect.Message {
	mi := &file_carModelIdf_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CarModel.ProtoReflect.Descriptor instead.
func (*CarModel) Descriptor() ([]byte, []int) {
	return file_carModelIdf_proto_rawDescGZIP(), []int{3}
}

func (x *CarModel) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CarModel) GetYear() string {
	if x != nil {
		return x.Year
	}
	return ""
}

func (x *CarModel) GetScore() float64 {
	if x != nil {
		return x.Score
	}
	return 0
}

var File_carModelIdf_proto protoreflect.FileDescriptor

var file_carModelIdf_proto_rawDesc = []byte{
	0x0a, 0x11, 0x63, 0x61, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x66, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x22, 0x4c, 0x0a, 0x0a, 0x49, 0x64, 0x66, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73,
	0x74, 0x12, 0x18, 0x0a, 0x07, 0x49, 0x6d, 0x67, 0x54, 0x79, 0x70, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x49, 0x6d, 0x67, 0x54, 0x79, 0x70, 0x65, 0x12, 0x24, 0x0a, 0x0d, 0x49,
	0x6d, 0x67, 0x55, 0x72, 0x6c, 0x4f, 0x72, 0x42, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x0d, 0x49, 0x6d, 0x67, 0x55, 0x72, 0x6c, 0x4f, 0x72, 0x42, 0x79, 0x74, 0x65,
	0x73, 0x22, 0x72, 0x0a, 0x0b, 0x49, 0x64, 0x66, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65,
	0x12, 0x0e, 0x0a, 0x02, 0x49, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x49, 0x64,
	0x12, 0x14, 0x0a, 0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x43, 0x6f, 0x6c, 0x6f, 0x72, 0x12, 0x1c, 0x0a, 0x04, 0x53, 0x69, 0x7a, 0x65, 0x18, 0x03,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x08, 0x2e, 0x43, 0x61, 0x72, 0x53, 0x69, 0x7a, 0x65, 0x52, 0x04,
	0x53, 0x69, 0x7a, 0x65, 0x12, 0x1f, 0x0a, 0x05, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0b, 0x32, 0x09, 0x2e, 0x43, 0x61, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x52, 0x05,
	0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x22, 0x5d, 0x0a, 0x07, 0x43, 0x61, 0x72, 0x53, 0x69, 0x7a, 0x65,
	0x12, 0x16, 0x0a, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05,
	0x52, 0x06, 0x48, 0x65, 0x69, 0x67, 0x68, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x4c, 0x65, 0x66, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x05, 0x52, 0x04, 0x4c, 0x65, 0x66, 0x74, 0x12, 0x10, 0x0a, 0x03,
	0x54, 0x6f, 0x70, 0x18, 0x03, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x54, 0x6f, 0x70, 0x12, 0x14,
	0x0a, 0x05, 0x57, 0x69, 0x64, 0x74, 0x68, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x52, 0x05, 0x57,
	0x69, 0x64, 0x74, 0x68, 0x22, 0x48, 0x0a, 0x08, 0x43, 0x61, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c,
	0x12, 0x12, 0x0a, 0x04, 0x4e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x12, 0x0a, 0x04, 0x59, 0x65, 0x61, 0x72, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x04, 0x59, 0x65, 0x61, 0x72, 0x12, 0x14, 0x0a, 0x05, 0x53, 0x63, 0x6f, 0x72,
	0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x53, 0x63, 0x6f, 0x72, 0x65, 0x32, 0x36,
	0x0a, 0x0b, 0x43, 0x61, 0x72, 0x4d, 0x6f, 0x64, 0x65, 0x6c, 0x49, 0x64, 0x66, 0x12, 0x27, 0x0a,
	0x08, 0x49, 0x64, 0x65, 0x6e, 0x74, 0x69, 0x66, 0x79, 0x12, 0x0b, 0x2e, 0x49, 0x64, 0x66, 0x52,
	0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x0c, 0x2e, 0x49, 0x64, 0x66, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x09, 0x5a, 0x07, 0x2e, 0x2f, 0x70, 0x72, 0x6f, 0x74,
	0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_carModelIdf_proto_rawDescOnce sync.Once
	file_carModelIdf_proto_rawDescData = file_carModelIdf_proto_rawDesc
)

func file_carModelIdf_proto_rawDescGZIP() []byte {
	file_carModelIdf_proto_rawDescOnce.Do(func() {
		file_carModelIdf_proto_rawDescData = protoimpl.X.CompressGZIP(file_carModelIdf_proto_rawDescData)
	})
	return file_carModelIdf_proto_rawDescData
}

var file_carModelIdf_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_carModelIdf_proto_goTypes = []interface{}{
	(*IdfRequest)(nil),  // 0: IdfRequest
	(*IdfResponse)(nil), // 1: IdfResponse
	(*CarSize)(nil),     // 2: CarSize
	(*CarModel)(nil),    // 3: CarModel
}
var file_carModelIdf_proto_depIdxs = []int32{
	2, // 0: IdfResponse.Size:type_name -> CarSize
	3, // 1: IdfResponse.Model:type_name -> CarModel
	0, // 2: CarModelIdf.Identify:input_type -> IdfRequest
	1, // 3: CarModelIdf.Identify:output_type -> IdfResponse
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_carModelIdf_proto_init() }
func file_carModelIdf_proto_init() {
	if File_carModelIdf_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_carModelIdf_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdfRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carModelIdf_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdfResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carModelIdf_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarSize); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_carModelIdf_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CarModel); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_carModelIdf_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_carModelIdf_proto_goTypes,
		DependencyIndexes: file_carModelIdf_proto_depIdxs,
		MessageInfos:      file_carModelIdf_proto_msgTypes,
	}.Build()
	File_carModelIdf_proto = out.File
	file_carModelIdf_proto_rawDesc = nil
	file_carModelIdf_proto_goTypes = nil
	file_carModelIdf_proto_depIdxs = nil
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConnInterface

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion6

// CarModelIdfClient is the client API for CarModelIdf service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type CarModelIdfClient interface {
	Identify(ctx context.Context, in *IdfRequest, opts ...grpc.CallOption) (*IdfResponse, error)
}

type carModelIdfClient struct {
	cc grpc.ClientConnInterface
}

func NewCarModelIdfClient(cc grpc.ClientConnInterface) CarModelIdfClient {
	return &carModelIdfClient{cc}
}

func (c *carModelIdfClient) Identify(ctx context.Context, in *IdfRequest, opts ...grpc.CallOption) (*IdfResponse, error) {
	out := new(IdfResponse)
	err := c.cc.Invoke(ctx, "/CarModelIdf/Identify", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CarModelIdfServer is the server API for CarModelIdf service.
type CarModelIdfServer interface {
	Identify(context.Context, *IdfRequest) (*IdfResponse, error)
}

// UnimplementedCarModelIdfServer can be embedded to have forward compatible implementations.
type UnimplementedCarModelIdfServer struct {
}

func (*UnimplementedCarModelIdfServer) Identify(context.Context, *IdfRequest) (*IdfResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Identify not implemented")
}

func RegisterCarModelIdfServer(s *grpc.Server, srv CarModelIdfServer) {
	s.RegisterService(&_CarModelIdf_serviceDesc, srv)
}

func _CarModelIdf_Identify_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IdfRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CarModelIdfServer).Identify(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/CarModelIdf/Identify",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CarModelIdfServer).Identify(ctx, req.(*IdfRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var _CarModelIdf_serviceDesc = grpc.ServiceDesc{
	ServiceName: "CarModelIdf",
	HandlerType: (*CarModelIdfServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Identify",
			Handler:    _CarModelIdf_Identify_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "carModelIdf.proto",
}
